[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "0.11.6"

[[constraint]]
  name = "github.com/linkedin/goavro"
  version = "2.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
