[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "0.9.4"

[[constraint]]
  name = "github.com/karrick/goavro"
  version = "0.3.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
